w3c/mediacapture-image

index.html
1. remove custom events (they are useless in Promise-based API)
2. output ImageBitmap instead of ImageData for grabFrame()
=> remove custom events & output ImageBitmap instead of ImageData for grabFrame()

index.html
Changed 'This document specific the takePhoto() and grabFrame() methods' to 'This document specifies the takePhoto() and grabFrame() methods'.
=> Minor tweak to index.html

index.html
=> autoWhiteBalanceMode and redEyeReduction changed to Boolean

index.html
And some minor editorial comments. Minimally rearranged the smaller interfaces into a logical progression: larger ones first, trivial ones afterwards. Introduced links to idl sections here and there for easier navigations.
This PR addresses #22 .
=> Change photoCapabilities into a Promise-based getPhotoCapabilities()

index.html
Reverts w3c/mediacapture-image#25
=> Revert "Fix name of Boolean to boolean per WebIDL"

index.html
=> Made all members of PhotoCapabilities readonly

index.html
=> Add optional PhotoSettings parameter to takePhoto()

index.html
necessary for disclosure / wg pages
possible for QuicInc home page
=> Use https links

index.html
To better reflect what the typical hardware provides.
=> Splitted 'auto' FocusMode into 'single-shot' and 'continuous'

index.html
...also made the whitespace indent consistent (4 spaces). Fix #56.
=> Use Promise-based MediaDevices.gUM() + cosmetic fixes

index.html
Discussion at https://github.com/webrtc/samples/issues/825#issuecomment-245210164
=> Replace MediaDevices. with navigator.mediaDevices.

index.html, index.js
... taking the chance to extract the reSpec dictionary into a file on its own. Also added to it a Participate Section, making it easy to browser/file Spec issues.
=> Added myself as co-editor, extracted reSpec config to index.js

index.html
=> navigator.MediaDevices -> navigator.mediaDevices

index.html
Tested to work in Chrome 55. Also addresses most of #64.
=> Fix Example 3, repeated frame grabbing

index.html
Reverts w3c/mediacapture-image#65.  Example 3 declarative syntax does not display properly.
=> Revert "Fix Example 3, repeated frame grabbing"

index.html
See individual commits and tagged issues by @fluffy
=> Some minor corrections from @fluffy's comments

index.html
Off with his head, and set it on York gates.
=> Removed optional parameter PhotoSettings from takePhoto() method (#86)

index.html
=> Fix example 3 for good

index.html
(my editor also removed superfluous whitespaces)
=> Added MediaSettingsRange.step member (#105)

index.html
Per https://github.com/w3c/mediacapture-image/pull/102#discussion_r83406122
=> rm obsolete comment

index.html
=> Add zoom example

index.html
=> Fix examples nits

implementation-status.md
more precise versioning for recent features
=> Cr implementation status, merged Linux and CrOs, corrections and

.gitignore, .travis.yml, Makefile
Per request from our chairs I am enabling the [WebRTC CI system](https://github.com/w3c/webrtc-respec-ci/) on all WebRTC and MediaCapture repos.
=> WebRTC CI system

index.bs
=> Introduce enum RedEyeReduction and use it in PhotoCapabilities

implementation-status.md
Same commit as e96197803746bf92fc93937b1a861901054d39bd
but this time against gh-pages.
=> Update implementation status (#166)

index.bs
@beaufortfrancois FYI, corrected as per discussion elsewhere.  Also updated Codepen.
=> Corrected/updated example 1 (#148)

index.bs
(and not to `gh-pages`, since there it isn't updated)
=> Make implementation-status.md link point to master branch

implementation-status.md, index.bs
=> Added getPhotoSettings() method and corrected literature

implementation-status.md
This PR cleans up a bit the implementation-status.md file: updates some milestones, inlines bug links and corrects some.
fyi @alexshalamov @dsanders11, since you'll need to (trivially) rebase your respective PRs.
=> Consolidate implementation status.md

index.bs
Per https://github.com/heycam/webidl/issues/365
=> Annotate interfaces with Exposed extended attribute

index.bs
Fix for https://github.com/w3c/mediacapture-image/issues/184. @yellowdoge PTAL.
=> Fix in-parallel steps to make sense.

implementation-status.md
Adding the exposureTime and focusDistance implementation status.
=> Fix implementation status

ptz-explainer.md
=> Fix nits in JS example

explainer.md
This PR fixes invalid JS example and prettifies with prettier.
=> Fixed JS example

index.bs
Fixes https://github.com/w3c/mediacapture-image/issues/252 and users `async`/`await` throughout.
=> Update examples using modern JS.

implementation-status.md
=> Update macOS support
