w3c/mediacapture-image

- index.html
This addresses #16. Also it removes a few superfluous empty spaces at the end of line -- my text editor is configured to do so and I didn't think it was a bad thing.
(Forget about #17, it was my mistake, took the wrong origin branch)
> Removed misleading photoSettings allusions in grabFrame()

- index.html
Some minor editorial changes and HTML formatting.
Note that this includes the s/specific/specifies/ change made by @samdutton in this [commit](https://github.com/w3c/mediacapture-image/commit/d17c94c289cc9c7824515c302d2427ae443f010b). 
Sam's patch landed in master branch, which is way behind gh-pages in w3c/capture-image, IOW, the W3C repo works in gh-pages mode (which makes sense so that the Editor's Draft stays current.
> Minor editorial comments and html formatting

- index.html
Rebasing #26 against gh-pages branch. Original description:
-------
This pull request transforms the markup to the new thing, because of the warning on the published version:
> Defining WebIDL in `dl` elements is deprecated. Please use Contiguous IDL instead: https://www.w3.org/respec/guide.html#contiguous-idl 
that seems to be affecting e.g. Section [methods](https://w3c.github.io/mediacapture-image/#methods): the text [is formatted wrong](http://imgur.com/BTWFyHr) and can't be read.
The text (i.e., what is not markup) is left untouched, except:
- [MediaSettingsItem](https://w3c.github.io/mediacapture-image/#mediasettingsitem), unused now, removed.
- Reflowed the text of the examples to make the indenting consistent.
No more ReSpec warnings! \o/
> Reformatting for contiguous WebIdl and reindenting/reflowing some sections (2nd try)

- index.html
Re. #32, I forgot escaping the < and > characters in the ImageCapture definition, this PR does it.
Also it adds some `<code></code>` and links in the first two sections.
(This is a refry on #35 that was tainted with other commits).
> Escape some < > symbols and other minor things (#35 again)

- index.html
Fixes #21. The only difference is the last sentence, added:
>If the UA can successfully apply the settings, the effect MAY be reflected, if visible at all, in <a><code>previewStream</code></a>.
> Added wording to say that setOptions() might be reflected in previewStream

- index.html
Adding `sequence<Point2D> pointsOfInterest` to [`photoSettings`](https://w3c.github.io/mediacapture-image/#PhotoSettings) allowing for defining the normalized `Point2D`s to be used as metering seeds for e.g. Focus. AutoExposure etc. Addresses #44.
> Adding sequence<Point2D> pointsOfInterest to photoSettings

- index.html
See the issue. Essentially, `imageWidth` and `imageHeight` are enumerated as two separate ranges ISO a lists of supported resolutions in order to prevent device fingerprinting and to allow the UA to make the best decision based on requests. Fixes #30.
> Added a note on why imageHeight and imageWidth are enumerated

- index.html
[Throws] is no longer a valid WebIDL extended attribute. In any case, it would not be applicable to a promise-returning function.
> Remove invalid [Throws] extended attribute

- index.html
Proposal to remove the low-level `ExposureMode` and instead use the typical OS level modes, see #49.
Also added `sharpness` entry to `PhotoCapabilities` attributes description, was only in the idl.
> Generalize FocusMode to MeteringMode and use it for `autoExposureMode`

- index.html
I just noticed while implementing `exposureCompensation`, the values of `min` and `current` can be negative (and, potentially, so could `max`). This small patch corrects that.
> Made MediaSettingsRange members signed (not unsigned).

- index.html
Added more literature around `exposureCompensation`: it's signed and is usually a symmetrical interval around 0, this value meaning no-compensation. Also, usually exposure comp values are floats, so they are enumerated as x100, and are expected like that too in PhotoSettings entries.
> Added comments on the actual values of exposureCompensation

- index.html
This PR suggest a correction to the (Auto) White Balance getter/setter. `PhotoSettings` says:
```
boolean       autoWhiteBalanceMode;
unsigned long whiteBalanceMode;
```
instead, is better to have `whiteBalanceMode` be a `MeteringMode` (i.e. `manual`, `continuous` etc.) and add a parameter `colorTemperature` to indicate its current/desired magnitude. This `colorTemperature` only applies when `whiteBalanceMode` is in manual mode.
> Converted whiteBalanceMode to MeteringMode and adding colorTemperature

- index.html
Just noticed during implementation of |colorTemperature| that this field
should be a MediaSettingsRange when considered a capability.
> |colorTemperature| should be a MediaSettingsRange

- index.html
Because when used in isolation, e.g. `setOptions({fillLightMode : 'on'});`,
"on" is not representative enough: it's confusing if it means "auto" or 
"always-on" or what.  setOptions({fillLightMode : 'torch'}); is more
self explanatory.
> FillLightMode 'on' should be called 'torch'

- index.html
... and also rewritten the 4 method's descriptions to be more Promise-based and homogeneous.
This is a quite a bit of a change, but I believe we can just take this chance to revamp up these few lines.  To ease reviewing, [1] contains a rendering of this PR.
[1] https://rawgit.com/Miguelao/mediacapture-image/prO__use_DOMException/index.html
> Removed ImageCaptureError in favour of DOMException

- implementation-status.md
Here are some nits addressed in this patch:
- ordered alphabetically PhotoCapabilities for easy lookup,
- added `pointsOfInterest` row
- moved `grabFrame` to the top
- moved `setOptions` to a separate row
- added `MediaSettingsRange.step` row
FIX: #107
> Polished Implementation status page

- implementation-status.md
- index.html
Examples update (#99, #62):
- Example 1 is now the zoom one (was: number 2), and I beefed it up
to have the needex HTML markup as well and have a takePhoto().
- Example 2 is now the repeated-grabbing-of-a-frame, no big changes,
just homogeneisation of variable names.
- Example 3 is now the grab-frame-and-postprocessing, which I made
work by bouncing the grabbed `imageBitmap` on a `canvas`. For the
purpose of the example, the colours are inverted.
- Also I homogeneised catch/then clause indenting and error reporting,
and inlined the superfluous `failedToGetMedia()`.
Finally I also added 3 codepen.io links (and a collection) with each
of the examples slightly modified, and added informative notes with
the links to the spec. Slightly modified means I added buttons to e.g.
start/stop capture …
> Update/cleanup examples (#99, #62).

- implementation-status.md
If I'm not mistaken, `MediaSettingsRange.step` was introduced in https://chromium.googlesource.com/chromium/src.git/+/8f17f7e85f0c37a5d6549ea252baa15b9653a974
According to https://chromium.googlesource.com/chromium/src/+/8f17f7e85f0c37a5d6549ea252baa15b9653a974/chrome/VERSION, Chrome version is:
```
MAJOR=56
MINOR=0
BUILD=2891
PATCH=0
> MediaSettingsRange.step shows up in M56

- index.html
...and removed entries mentioning a x100 multiplier to avoid floating point.
Note that the [float](https://heycam.github.io/webidl/#idl-float) idl definition mentions:
> Unless there are specific reasons to use a 32 bit floating point type, specifications should use double rather than float, since the set of values that a double can represent more closely matches an ECMAScript Number.
but I feel that `float` can represent all of our value ranges and is smaller in size.
> (#77) s/long/double/ in MediaSettingsRange

- index.html
I forgot to s/unsigned long/double/ in the `PhotoSettings`, but they need to change accordingly.
> Follow up #77 (pr #120), s/unsigned long/double/ in PhotoSettings dictionary

- index.html
Made `Point2D` general and moved its semantics to the `pointsOfInterest` entry.
Also changed the `Point2D` attributes from `float` to `double`.
> Made Point2D general and moved its semantics to the pointsOfInterest entry (#125)

- index.html
- index.js
Correction to what I wrote in #128: 
> On the plus side, controls provide max,min, and default values, which would answer part of your question -- but now e.g. what would negative values do.
On second readings the UVC specifies the orientation of the scale by indicating that `increasing values indicate increasing {brightness, contrast, saturation, sharpness}`; I'm reflecting that in the document now.
Again, note that the individual `photoCapabilities` discussion is non-normative.
> Added UVC informative ref and further defined the associated fields (#128)

- index.html
Added literature on how setOptions() and grabFrame() interact with constraints (#130). 
Cleaned up webidl dfn links.
> setOptions()/grabFrame() and MediaStreamTrack's constraints

- index.bs
This is not allowed per the Web IDL syntax:
https://heycam.github.io/webidl/#idl-enums
> Remove trailing commas from enums

- index.bs
they made it all the way to https://www.w3.org/TR/tr-date-all
> remove title quotes

- implementation-status.md
- index.bs
As promised in issue #177.
Only real thing I can think of worth debating is whether to have the setting value be degrees, or arc seconds. They're trivial to convert between, and in UVC it is defined as arc seconds, as well as in more of the Windows APIs.
Degrees would be more intuitive for users, but since the underlying API will be returning the `max`/`min`/`step` in arc seconds, the `MediaSettingsRange` may look quite odd if you convert it to degrees, like from `-38.23` to `38.23` with steps of `0.453`. That could also lead to rounding problems in the conversion if the `step` in arc seconds is say 1000, that would be 0.277778 degrees, which is icky to deal with. As long as the camera "snaps" to the nearest valid step the rounding problems matter less, although it's never a great idea to …
> Add pan and tilt constraints

- index.bs
The mailing list "public-media-capture" is not active anymore and has
been effectively replaced by public-webrtc. This change updates the
information on the spec.
> Change mailing-list to public-webrtc

- .travis.yml
According to https://travis-ci.com/github/w3c/mediacapture-image/builds/154272334, `bikeshed requires Python '>=3.7' but the running Python is 2.7.15`. This PR updates python version in Travis from 2.7 to 3.7.
> Update python version in Travis

- index.bs
Our model of thinking has been :
The Pan-Tilt-Zoom permission can only be requested (and only shown in the prompt) if the currently connected/selected camera supports it.
Camera permission without PTZ (obtained using an older version of the user agent, or with another camera) is not implicitly upgraded to Camera permission with PTZ (even if the hardware supports it). The permission has to be re-requested.
In w3ctag/design-reviews#358, TAG wants to make sure that from the web app’s perspective: Pan-Tilt-Zoom needs to be explicitly requested as an extension to video capture permission.
To facilitate the previous requirements we want to add a new CameraDevicePermissionDescriptor dictionary introduced in w3c/permissions/pull/204 to differentiate between the two cases and to modify media …
> Update pan, tilt and zoom constraints

- index.bs
Hopefully this clarifies the spec and resolves the concerns raised in #225.
There are no functional or algorithmic changes as that is the consensus reached during discussion in #225 as I understood.
> Clarify pan/tilt/zoom constraints (#225)

- ptz-explainer.md
As discussed in https://github.com/w3c/mediacapture-image/issues/223#issuecomment-638801894, this PR requires PTZ permission to be granted for `applyConstraints()`.
> Require PTZ permission for applyConstraints()

- ptz-explainer.md
As discussed with @guidou, we should make it clear how `getUserMedia()` can reject when PTZ constraints are required.
This currently means `getUserMedia({video: {pan: 1}})` for instance rejects with an `OverConstrainedError`. We should think about how to make sure we don't leak camera PTZ capabilities when user didn't grant access yet.
@reillyeon @eehakkin @riju @andypaicu
> Define when gUM rejects with required PTZ constraints

- ptz-explainer.md
This PR fixes a nit I forgot to update in https://github.com/w3c/mediacapture-image/pull/227
> applyConstraints doesn't ask for camera PTZ access

- index.bs
This PR simply adds a default toJSON() to MediaSettingsRange so that web developers simply interesting in logging capabilities can do so with `JSON.stringify(myTrack.getCapabilities())`.
It was done for MediaDeviceInfo previously. See https://w3c.github.io/mediacapture-main/#dom-mediadeviceinfo-tojson
> Add toJSON() for MediaSettingsRange

- index.bs
- ptz-explainer.md
This PR updates spec and explainer to reject applyConstraints with SecurityError if page is not visible for pan, tilt, and zoom.
FIX https://github.com/w3c/mediacapture-image/issues/236
> Reject applyConstraints if page is not visible for PTZ

- index.bs
Following [blink-dev discussion](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/AqKdWOB7O8c), it seems preferable to have `MediaSettingsRange` & `PhotoCapabilities` interfaces defined as dictionaries instead of [adding toJSON() to MediaSettingsRange](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fw3c%2Fmediacapture-image%2Fpull%2F234&sa=D&sntz=1&usg=AFQjCNHZaDQWtbUHm5XJWTotUdkjUiN6cg).
This PR changes `MediaSettingsRange` & `PhotoCapabilities` interfaces to dictionaries, and therefore removes specific `toJSON()` from `MediaSettingsRange`.
With this change, `JSON.stringify(myTrack.getCapabilities())` and `JSON.stringify(await myImageCapture.getPhotoCapabilities())` will continue to help web developers interested in easily logging and aggregating media capture …
> Change MediaSettingsRange & PhotoCapabilities interfaces to dictionaries

- index.bs
This PR fixes build warnings below raised by bikeshed:
```
WARNING: The following <var>s were only used once in the document:
'width'
'height'
'manual'
'sharpness'
'off'
'on'
If these are not typos, please add an ignore='' attribute to the <var>.
```
> Fix build warnings

- index.bs
Pan and tilt ranges should be from -180\*3600 to 180\*3600 arc seconds instead of from -180*3600* to 180*3600* arc seconds.
> Fix arc second range presentations

- index.bs
Split from https://github.com/w3c/mediacapture-image/pull/248 per @youennf's request.
> Clarify pan/tilt/zoom capabilities (#245)

- ptz-explainer.md
This PR updates the PTZ explainer with the resolution "06" at https://www.w3.org/2020/09/15-webrtc-minutes.html#r06
I believe @eehakkin will follow with spec changes.
@jan-ivar @youennf @riju
> Allow empty PTZ capabilities without PTZ permission

- ptz-explainer.md
This PR updates the PTZ explainer with the resolution "05" at https://www.w3.org/2020/09/15-webrtc-minutes.html#r05
I believe @eehakkin will follow with spec changes.
@jan-ivar @youennf @riju
> Allow only ideal PTZ constraints in gUM

- index.bs
Split from https://github.com/w3c/mediacapture-image/pull/248 per @youennf's request.
> Clarify pan/tilt/zoom settings (#245)

- ptz-explainer.md
https://github.com/w3c/mediacapture-image/pull/261 says getUserMedia with mandatory PTZ constraints in basic set should return a promise that rejects with `TypeError`, not `OverConstrainedError` anymore. This PR fixes https://github.com/w3c/mediacapture-image/issues/229
> Replace OverConstrainedError with TypeError

- index.bs
This PR fixes nits in PTZ example:
- Use `settings` instead of `capabilities` for checking whether PTZ is available.
- Use `disabled` instead of custom CSS class `hidden` for clarity
- Remove use of template literal as bikeshed doesn't like it. See current state at https://w3c.github.io/mediacapture-image/#example1
@riju Please review and merge.
> Fix nits in PTZ example

- index.bs
This fixes to typos:
- the double constraint dictionary type is `ConstrainDoubleRange` not `ConstrainDouble` which is the name of the typedef.
- The pan and tilt value range lower bounds should be -180\*3600 instead of en dash 180\*3600.
@riju PTAL.
> Fix dictionary name and minus sign typos

- index.bs
The removal was requested at https://github.com/w3c/mediacapture-image/pull/260#discussion_r495232131.
PTAL @jan-ivar & @youennf.
> Remove a request permission to use algorithm note

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-image/pull/274.html" title="Last updated on Feb 9, 2021, 10:04 AM UTC (88937d0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-image/274/7a1e01d...88937d0.html" title="Last updated on Feb 9, 2021, 10:04 AM UTC (88937d0)">Diff</a>
> Fix mixed up definitions of imageWidth and imageHeight

- index.bs
Fixes #256. This along with https://github.com/w3c/mediacapture-main/pull/742 is to clarify meaning of PTZ constraints presence.
***
<a href="https://pr-preview.s3.amazonaws.com/eehakkin/intel-w3c-mediacapture-image/pull/271.html" title="Last updated on Mar 16, 2021, 2:40 PM UTC (3bef8ed)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-image/271/72ee760...eehakkin:3bef8ed.html" title="Last updated on Mar 16, 2021, 2:40 PM UTC (3bef8ed)">Diff</a>
> Replace PTZ boolean normalization with boolean constraints

- index.bs
Fixes https://github.com/w3c/mediacapture-image/issues/245. This is to address https://www.w3.org/2020/09/15-webrtc-minutes.html#r06
***
<a href="https://pr-preview.s3.amazonaws.com/eehakkin/intel-w3c-mediacapture-image/pull/260.html" title="Last updated on Feb 15, 2021, 7:19 AM UTC (3006eb1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-image/260/72ee760...eehakkin:3006eb1.html" title="Last updated on Feb 15, 2021, 7:19 AM UTC (3006eb1)">Diff</a>
> Allow PTZ support to be always exposed in capabilities

- index.bs
part of #295
***
<a href="https://pr-preview.s3.amazonaws.com/dontcallmedom/repo-manager/pull/296.html" title="Last updated on Dec 7, 2022, 4:05 PM UTC (4855418)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-image/296/a93cbbe...dontcallmedom:4855418.html" title="Last updated on Dec 7, 2022, 4:05 PM UTC (4855418)">Diff</a>
> Fix link to camera permission name

- index.bs
The anchors are no longer needed now that Bikeshed's xref database contains the definitions from Media Capture and Streams, and some of the underlying URLs are outdated.
The few explicit anchors that remain link to definitions that are not (yet?) exported by Media Capture and Streams.
(Note the remaining "link-default" is because Bikeshed still has Page Visibility in its database. That spec was merged into HTML, so reference should now go to HTML)
This should fix #295.
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/mediacapture-image/pull/297.html" title="Last updated on Dec 7, 2022, 6:59 PM UTC (28fab85)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-image/297/6c99181...tidoust:28fab85.html" title="Last updated on Dec 7, 2022, 6:59 PM UTC …
> Drop most explicit anchors from Bikeshed settings

- README.md
- index.bs
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Feb 20, 2023, 3:03 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FFluorescentHallucinogen%2Fmediacapture-image%2F3cbf00cde13f698dc069fafc450b477367cfad37%2Findex.bs&force=1&md-warning=not%20ready)
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1> …
```
> Update Image Capture polyfill

- index.bs
see also https://github.com/w3c/mediacapture-main/pull/968 fixes #302
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-image/pull/303.html" title="Last updated on Aug 25, 2023, 9:30 AM UTC (ef9b7b6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-image/303/5ea2a91...ef9b7b6.html" title="Last updated on Aug 25, 2023, 9:30 AM UTC (ef9b7b6)">Diff</a>
> Remove usage of no-longer defined DevicePermissionDescriptor/deviceId

- .github/workflows/auto-publish.yml
- index.bs
The `paths:` is not a trigger but a restriction for the `push:` trigger.
There should be no relic `</a>` tags without the corresponding `<a>` tags.
> Fix auto publish workflow and spec format
